name: pelvis_seg
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python版本
  - python=3.10
  
  # 核心深度学习框架
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1
  - pytorch-lightning=2.5.0
  
  # 医学图像处理
  - simpleitk
  - nibabel=5.3.2
  - pydicom=3.0.1
  - itk=5.4.2
  
  # 图像处理
  - opencv=4.11.0
  - scikit-image=0.25.2
  - pillow=11.1.0
  - imageio=2.37.0
  
  # 科学计算
  - numpy=1.26.4
  - scipy=1.15.2
  - pandas=2.2.3
  - scikit-learn=1.6.1
  
  # 可视化
  - matplotlib=3.9.1
  - vtk=9.2.2
  - seaborn=0.13.2
  
  # GUI
  - pyqt
  
  # 工具
  - tqdm
  - pyyaml=6.0.2
  - tensorboard=2.19.0
  
  # pip 安装的包
  - pip
  - pip:
    - monai==1.4.0
    - dicom2nifti==2.5.1
    - loguru==0.7.2